spring:
  application:
    name: fulfill-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.64.14:8848
        username: nacos
        password: nacos

server:
  port: 8050

dubbo:
  registry:
    address: nacos://192.168.64.14:8848
  consumer:
    timeout: 3000
  protocol:
    port: 20882

seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.64.14:8848
      group: DEFAULT_GROUP
      namespace: ""
      username: nacos
      password: nacos
  tx-service-group: fulfill_tx_group
  service:
    vgroup-mapping:
      fulfill_tx_group: default
