spring:
  datasource:
    password: root
    username: root
    url: jdbc:mysql://192.168.64.14:3307/cart-service?characterEncoding=utf8&connectTimeout=1000&socketTimeout=30000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: cart-service
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.64.14:8848
        username: nacos
        password: nacos
server:
  port: 8060

dubbo:
  registry:
    address: nacos://192.168.64.14:8848
  consumer:
    timeout: 3000
  protocol:
    port: 20883

seata:
  registry:
    type: nacos
    nacos:
      application: seata-server
      server-addr: 192.168.64.14:8848
      group: DEFAULT_GROUP
      namespace: ""
      username: nacos
      password: nacos
  tx-service-group: cart_tx_group
  service:
    vgroup-mapping:
      cart_tx_group: default
